name: Java CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: # To run it manually for testing

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'
  WORKING_DIR: '.'

jobs:
  # ===========================================
  # STAGE 1: Build & Unit Test
  # ===========================================
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Build and Run Tests
        working-directory: ${{ env.WORKING_DIR }}
        run: mvn clean test -B

      # We upload the target folder so the Quality stage doesn't have to re-compile
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.WORKING_DIR }}/target/
          retention-days: 1

  # ===========================================
  # STAGE 2: Quality gate
  # ===========================================
  quality-gate:
    name: "Quality gate"
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      # ===========================================
      # Steps to execute on push
      # ===========================================
      - name: Run Checkstyle
        if: github.event_name == 'push'
        working-directory: ${{ env.WORKING_DIR }}
        run: mvn checkstyle:check -Pcheckstyle -B

      - name: Run PMD
        if: github.event_name == 'push'
        working-directory: ${{ env.WORKING_DIR }}
        run: mvn pmd:check -Ppmd -B

      - name: Run Spotbugs
        if: github.event_name == 'push'
        working-directory: ${{ env.WORKING_DIR }}
        run: mvn spotbugs:check -Pspotbugs -B

      # ===========================================
      # Steps to execute on Pull Requests
      # ===========================================
      - name: Run Checkstyle with Reviewdog
        if: github.event_name == 'pull_request'
        uses: dbelyaev/action-checkstyle@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
          checkstyle_version: "13.3.0"
          checkstyle_config: ./config/checkstyle/checkstyle_checks.xml
          level: 'error'
          filter_mode: 'nofilter'

      - name: Run PMD with Reviewdog
        if: github.event_name == 'pull_request'
        uses: kemsakurai/action-pmd@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
          checkstyle_version: "13.3.0"
          checkstyle_config: config/pmd/pmd_ruleset.xml
          level: 'error'
          filter_mode: 'nofilter'


          # We upload the target folder so the Quality stage doesn't have to re-compile
          #      - name: Upload Build Artifacts
          #        uses: actions/upload-artifact@v4
          #        with:
          #          name: build-output
          #          path: ${{ env.WORKING_DIR }}/target/
          #          retention-days: 1

          #- name: Run PMD with Reviewdog
          #  uses: kemsakurai/action-pmd@v0.1.0
          #  with:
          #    github_token: ${{ secrets.GITHUB_TOKEN }}
          #    reporter: 'github-pr-review'
          #rulesets_path: 'config/pmd/pmd-ruleset.xml'
          #    tool_name: 'pmd_reviewdog'
          #    level: 'warning'
          #    filter_mode: 'nofilter'
          #pmd_xml: target/pmd.xml
